# ----------------------------
# Makefile Options
# ----------------------------

NAME = TIMANAG
ICON = icon.png
DESCRIPTION = "App for managing settings"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
